spring:
  application:
    name: spring-cloud-eureka-core
server:
  port: 8076
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true