version: "3"
services:
  schedapp:
    image: schedapp
    restart: on-failure
    environment:
      - WAIT_HOSTS=mysql:3307
      - WAIT_HOSTS_TIMEOUT=500
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    ports:
      - "8080:8080"
    networks:
      - user-mysql
    depends_on:
      - sched_db

  sched_db:
    hostname: mysql
    restart: always
    image: mysql:8
    networks:
      - user-mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=aw4cha3vaith
      - MYSQL_DATABASE=schedapp

networks:
  user-mysql: